import { useEffect, useMemo, useState } from 'react';
import { Icon } from '../components/Icon';
import { ConfirmDialog } from '../components/ui/ConfirmDialog';
import { adminData } from '../services/adminData';

type Resource='reviews'|'discounts'|'returns'|'payments'|'shipping'|'notifications'|'administrators'|'roles'|'audit-logs';
const META:Record<Resource,[string,string,string]> = {
  reviews:['Growth','Reviews','Moderate customer feedback and protect storefront quality.'], discounts:['Growth','Discounts','Create controlled promotions with timing and usage limits.'], returns:['Operations','Returns','Review requests and track the refund lifecycle.'], payments:['Operations','Payments','Monitor provider state, transactions and refunds.'], shipping:['Operations','Shipping','Configure delivery methods and customer-facing delivery rules.'], notifications:['Operations','Notifications','Manage customer communication and storefront events.'], administrators:['Control','Administrators','Manage access to sensitive ORYN commerce operations.'], roles:['Control','Roles & permissions','Define what each administrator can see and change.'], 'audit-logs':['Control','Audit logs','Trace sensitive administrator activity.']
};
const date=(v:any)=>v?new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—';
const money=(v:any)=>`$${Number(v??0).toFixed(2)}`;
function Status({v}:{v:string}){return <span className={`status ${String(v).toLowerCase().replaceAll('_','-')}`}>{String(v).replaceAll('_',' ')}</span>}

export function OperationsWorkspace({resource}:{resource:Resource}) {
  const [rows,setRows]=useState<any[]>([]), [q,setQ]=useState(''), [loading,setLoading]=useState(true), [error,setError]=useState('');
  const [editor,setEditor]=useState<{type:'create'|'edit'|'manage';item?:any}|null>(null); const [confirm,setConfirm]=useState<any>(null); const [busy,setBusy]=useState(false);
  async function load(){setLoading(true);setError('');try{const r=resource==='reviews'?await adminData.reviews():resource==='discounts'?await adminData.coupons():resource==='returns'?await adminData.returns():resource==='payments'?await adminData.payments():resource==='shipping'?await adminData.shipping():resource==='notifications'?await adminData.notifications():resource==='administrators'?await adminData.administrators():resource==='roles'?await adminData.roles():await adminData.auditLogs();setRows(r.data?.items??r.data??[])}catch(e){setError(e instanceof Error?e.message:'Unable to load')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[resource]);
  const filtered=useMemo(()=>!q?rows:rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q.toLowerCase())),[rows,q]);
  async function remove(){if(!confirm)return;setBusy(true);try{if(resource==='shipping')await adminData.deleteShipping(confirm.id);if(resource==='notifications')await adminData.deleteNotification(confirm.id);if(resource==='administrators')await adminData.deleteAdministrator(confirm.id);if(resource==='roles')await adminData.deleteRole(confirm.id);setConfirm(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete record')}finally{setBusy(false)}}
  if(loading)return <div className="state-view"><div className="loader-line"/><p>Loading {META[resource][1].toLowerCase()}…</p></div>;
  if(error)return <div className="state-view"><p>{error}</p><button className="secondary-btn" onClick={load}>Retry</button></div>;
  const canCreate=['discounts','shipping','notifications','administrators','roles'].includes(resource);
  return <div className="operations-page"><div className="page-intro"><div><p className="eyebrow">{META[resource][0]}</p><h2>{META[resource][1]}</h2><p>{META[resource][2]}</p></div>{canCreate&&<button className="primary-btn" onClick={()=>setEditor({type:'create'})}><Icon name="Plus" size={15}/> Create</button>}</div>
    <div className="toolbar"><div className="search-field"><Icon name="Search" size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={`Search ${META[resource][1].toLowerCase()}…`}/></div><button className="secondary-btn" onClick={load}><Icon name="RefreshCw" size={15}/> Refresh</button></div>
    <section className="panel table-panel"><div className="table-wrap">{resource==='shipping'?<Shipping rows={filtered} onEdit={item=>setEditor({type:'edit',item})} onDelete={item=>setConfirm({id:item.id,title:'Delete shipping method?',description:'This delivery method will be removed from ORYN checkout.',label:'Delete'})}/>:resource==='roles'?<Roles rows={filtered} onManage={item=>setEditor({type:'manage',item})} onDelete={item=>setConfirm({id:item.id,title:'Delete role?',description:'A role can only be deleted when no administrator is assigned to it.',label:'Delete'})}/>:<Table resource={resource} rows={filtered} refresh={load} onDelete={(item)=>setConfirm({id:item.id,title:`Delete ${resource.slice(0,-1)}?`,description:'This record will be permanently removed. This action cannot be undone.',label:'Delete'})}/>}</div>{!filtered.length&&<div className="ops-empty"><Icon name="Inbox" size={24}/><strong>No records yet</strong><span>Live records will appear here when ORYN has activity.</span></div>}</section>
    {editor&&<OperationsDialog resource={resource} mode={editor.type} item={editor.item} close={()=>setEditor(null)} saved={()=>{setEditor(null);void load()}}/>}
    <ConfirmDialog open={!!confirm} title={confirm?.title??''} description={confirm?.description??''} confirmLabel={busy?'Deleting…':confirm?.label??'Delete'} danger onClose={()=>!busy&&setConfirm(null)} onConfirm={remove}/>
  </div>
}

function Table({resource,rows,refresh,onDelete}:{resource:Resource;rows:any[];refresh:()=>void;onDelete:(item:any)=>void}){
 if(resource==='reviews')return <table><thead><tr><th>Customer</th><th>Product</th><th>Rating</th><th>Date</th><th>Status</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.user?.firstName} {r.user?.lastName}</strong><small className="cell-sub">{r.user?.email}</small></td><td>{r.product?.name}</td><td>{r.rating}.0 ★</td><td>{date(r.createdAt)}</td><td><Status v={r.approved?'Published':'Pending'}/></td><td><div className="action-group">{!r.approved&&<button className="mini-btn" onClick={async()=>{await adminData.updateReview(r.id,{approved:true});refresh()}}>Approve</button>}{r.approved&&<button className="mini-btn" onClick={async()=>{await adminData.updateReview(r.id,{approved:false});refresh()}}>Unpublish</button>}</div></td></tr>)}</tbody></table>;
 if(resource==='discounts')return <table><thead><tr><th>Code</th><th>Type</th><th>Value</th><th>Starts</th><th>Expires</th><th>Uses</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong className="mono">{r.code}</strong></td><td>{r.type}</td><td>{r.type==='PERCENTAGE'?`${r.value}%`:money(r.value)}</td><td>{date(r.startsAt)}</td><td>{r.expiresAt?date(r.expiresAt):'No expiry'}</td><td>{r.usages?.length??0}</td><td><Status v={r.active?'Active':'Paused'}/></td></tr>)}</tbody></table>;
 if(resource==='returns')return <table><thead><tr><th>Return</th><th>Customer</th><th>Order</th><th>Reason</th><th>Status</th><th>Date</th><th>Update</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="mono">{r.id.slice(-8).toUpperCase()}</td><td>{r.user?.firstName} {r.user?.lastName}</td><td className="mono">{r.orderId.slice(-8).toUpperCase()}</td><td>{r.reason}</td><td><Status v={r.status}/></td><td>{date(r.createdAt)}</td><td><select className="inline-select" value={r.status} onChange={async e=>{await adminData.updateReturn(r.id,{status:e.target.value});refresh()}}><option>REQUESTED</option><option>APPROVED</option><option>REJECTED</option><option>RECEIVED</option><option>REFUNDED</option><option>CANCELLED</option></select></td></tr>)}</tbody></table>;
 if(resource==='payments')return <table><thead><tr><th>Payment</th><th>Order</th><th>Provider</th><th>Amount</th><th>Transactions</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="mono">{r.id.slice(-9).toUpperCase()}</td><td className="mono">{r.orderId.slice(-8).toUpperCase()}</td><td>{r.provider}</td><td>{money(r.amount)} {r.currency}</td><td>{r.transactions?.length??0}</td><td><Status v={r.status}/></td></tr>)}</tbody></table>;
 if(resource==='notifications')return <table><thead><tr><th>Notification</th><th>Customer</th><th>Type</th><th>Read</th><th>Date</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.title}</strong><small className="cell-sub">{r.body}</small></td><td>{r.user?.firstName} {r.user?.lastName}</td><td><Status v={r.type}/></td><td>{r.readAt?'Read':'Unread'}</td><td>{date(r.createdAt)}</td><td><button className="table-action danger" onClick={()=>onDelete(r)}>Delete</button></td></tr>)}</tbody></table>;
 if(resource==='administrators')return <table><thead><tr><th>Administrator</th><th>Role</th><th>Email</th><th>Status</th><th>Joined</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.firstName} {r.lastName}</strong></td><td>{r.role?.name}</td><td>{r.email}</td><td><Status v={r.status}/></td><td>{date(r.createdAt)}</td><td>{r.role?.name!=='Platform Owner'&&<button className="table-action danger" onClick={()=>onDelete(r)}>Delete</button>}</td></tr>)}</tbody></table>;
 return <table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Resource</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.createdAt).toLocaleString()}</td><td><strong>{r.actor?.firstName} {r.actor?.lastName}</strong></td><td>{r.action}</td><td>{r.resource}</td></tr>)}</tbody></table>
}
function Shipping({rows,onEdit,onDelete}:{rows:any[];onEdit:(item:any)=>void;onDelete:(item:any)=>void}){return <div className="shipping-cards">{rows.map(r=><article className="shipping-card" key={r.id}><div className="shipping-icon"><Icon name="Truck" size={18}/></div><div className="shipping-main"><div><p className="eyebrow">Delivery method</p><h3>{r.name}</h3><p>{r.description||'ORYN delivery option.'}</p></div><Status v={r.active?'Active':'Paused'}/></div><div className="shipping-meta"><div><span>Price</span><strong>{money(r.price)}</strong></div><div><span>Updated</span><strong>{date(r.updatedAt)}</strong></div></div><div className="shipping-actions"><button className="secondary-btn" onClick={()=>onEdit(r)}><Icon name="Pencil" size={13}/> Edit</button><button className="secondary-btn danger-outline" onClick={()=>onDelete(r)}><Icon name="Trash2" size={13}/> Delete</button></div></article>)}</div>}
function Roles({rows,onManage,onDelete}:{rows:any[];onManage:(item:any)=>void;onDelete:(item:any)=>void}){return <div className="role-grid">{rows.map(r=><article className="role-card" key={r.id}><p className="eyebrow">Role</p><h3>{r.name}</h3><p>{r.users?.length??0} members · {r.permissions?.length??0} permissions</p><div className="permission-stack">{(r.permissions??[]).slice(0,8).map((p:any)=><span key={p.permissionId}>{p.permission?.key}</span>)}</div><div className="role-actions"><button className="secondary-btn" onClick={()=>onManage(r)}>Manage <Icon name="ArrowRight" size={14}/></button><button className="icon-btn danger" onClick={()=>onDelete(r)} aria-label={`Delete ${r.name}`}><Icon name="Trash2" size={15}/></button></div></article>)}</div>}

function OperationsDialog({resource,mode,item,close,saved}:{resource:Resource;mode:'create'|'edit'|'manage';item?:any;close:()=>void;saved:()=>void}){
 const [f,setF]=useState<any>(item??{}); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 async function submit(){setBusy(true);setError('');try{
   if(resource==='shipping') await (mode==='edit'?adminData.updateShipping(item.id,{name:f.name,description:f.description||null,price:Number(f.price),active:!!f.active}):adminData.createShipping({name:f.name,description:f.description||null,price:Number(f.price),active:true}));
   if(resource==='discounts') await adminData.createCoupon({code:f.code,type:f.type||'PERCENTAGE',value:Number(f.value),startsAt:f.startsAt||new Date().toISOString(),expiresAt:f.expiresAt||null,maxUses:f.maxUses?Number(f.maxUses):null,active:true});
   if(resource==='notifications') await adminData.createNotification({userId:f.userId,type:f.type,title:f.title,body:f.body,deepLink:f.deepLink||null});
   if(resource==='roles' && mode==='create') await adminData.createRole({name:f.name});
   if(resource==='administrators') await adminData.createAdministrator({firstName:f.firstName,lastName:f.lastName,email:f.email,password:f.password,roleId:f.roleId});
   saved();
 }catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}}
 const title=mode==='manage'?'Role permissions':mode==='edit'?'Edit shipping method':'Create '+META[resource][1].slice(0,-1);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)close()}}><div className="modal admin-dialog"><div className="modal-head"><div><p className="eyebrow">{META[resource][0]}</p><h3>{title}</h3></div><button className="icon-btn" onClick={close} aria-label="Close"><Icon name="X"/></button></div>{error&&<div className="notice error-notice">{error}</div>}<div className="modal-body">
   {resource==='shipping'&&<><label>Name<input value={f.name??''} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Description<textarea value={f.description??''} rows={4} onChange={e=>setF({...f,description:e.target.value})}/></label><label>Price<input type="number" min="0" value={f.price??0} onChange={e=>setF({...f,price:e.target.value})}/></label>{mode==='edit'&&<label>Active<select value={f.active?'true':'false'} onChange={e=>setF({...f,active:e.target.value==='true'})}><option value="true">Active</option><option value="false">Paused</option></select></label>}</>}
   {resource==='discounts'&&<><label>Code<input value={f.code??''} onChange={e=>setF({...f,code:e.target.value.toUpperCase()})}/></label><label>Type<select value={f.type??'PERCENTAGE'} onChange={e=>setF({...f,type:e.target.value})}><option>PERCENTAGE</option><option>FIXED</option></select></label><label>Value<input type="number" min="0" value={f.value??''} onChange={e=>setF({...f,value:e.target.value})}/></label><label>Expires<input type="datetime-local" value={f.expiresAt??''} onChange={e=>setF({...f,expiresAt:e.target.value?new Date(e.target.value).toISOString():''})}/></label></>}
   {resource==='notifications'&&<><label>User ID<input value={f.userId??''} onChange={e=>setF({...f,userId:e.target.value})}/></label><label>Type<input value={f.type??'ADMIN_MESSAGE'} onChange={e=>setF({...f,type:e.target.value})}/></label><label>Title<input value={f.title??''} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Body<textarea value={f.body??''} rows={5} onChange={e=>setF({...f,body:e.target.value})}/></label><label>Deep link<input value={f.deepLink??''} onChange={e=>setF({...f,deepLink:e.target.value})}/></label></>}
   {resource==='roles'&&<>{mode==='create'?<label>Name<input value={f.name??''} onChange={e=>setF({...f,name:e.target.value})}/></label>:<><div className="role-summary"><strong>{item?.name}</strong><span>{item?.users?.length??0} assigned administrators</span></div><div className="permission-detail-list">{(item?.permissions??[]).map((p:any)=><div key={p.permissionId}><Icon name="Check" size={14}/><span><strong>{p.permission?.key}</strong><small>{p.permission?.description??'Permission available to this role.'}</small></span></div>)}{!(item?.permissions?.length) && <div className="ops-empty"><Icon name="KeyRound" size={22}/><strong>No permissions assigned</strong><span>Permissions can be assigned once the role policy editor is enabled.</span></div>}</div></>}</>}
   {resource==='administrators'&&<><label>First name<input value={f.firstName??''} onChange={e=>setF({...f,firstName:e.target.value})}/></label><label>Last name<input value={f.lastName??''} onChange={e=>setF({...f,lastName:e.target.value})}/></label><label>Email<input type="email" value={f.email??''} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Password<input type="password" value={f.password??''} onChange={e=>setF({...f,password:e.target.value})}/></label><label>Role ID<input value={f.roleId??''} onChange={e=>setF({...f,roleId:e.target.value})}/></label></>}
 </div><div className="modal-actions"><button className="secondary-btn" onClick={close}>Close</button>{mode!=='manage'&&<button className="primary-btn" disabled={busy} onClick={submit}>{busy?'Saving…':'Save'}</button>}</div></div></div>
}
