import { Bell, ChevronRight, Heart, LogOut, MapPin, Package, Settings, ShieldCheck, UserRound } from 'lucide-react-native';
import type { ReactNode } from 'react';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';
import { colors, spacing, typography } from '@/theme';
import { Text } from '@/components/ui';
import { AccountRow } from '@/components/account/AccountRow';
import { useNotificationStore } from '@/store/notificationStore';
import { useAuthStore } from '@/store/authStore';

export default function ProfileScreen() {
  const user = useAuthStore((state) => state.user); const logout = useAuthStore((state) => state.logout); const unread = useNotificationStore((state) => state.items.filter((item) => !item.readAt).length);
  return <View style={styles.container}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>ORYN / ACCOUNT</Text><Text style={styles.title}>Your account</Text></View><Pressable onPress={() => router.push('/notifications')} style={styles.bell}><Bell size={19} color={colors.text}/>{unread ? <View style={styles.dot}/> : null}</Pressable></View>
    <Pressable style={styles.identity} onPress={() => router.push('/profile/edit')}><View style={styles.avatar}><Text style={styles.avatarText}>{user?.firstName?.[0]?.toUpperCase() ?? 'O'}</Text></View><View style={styles.identityCopy}><Text style={styles.name}>{user ? `${user.firstName} ${user.lastName}` : 'ORYN customer'}</Text><Text style={styles.email}>{user?.email ?? ''}</Text></View><ChevronRight size={18} color={colors.textMuted}/></Pressable>
    <Section title="ORDERS & SAVED"><AccountRow icon={Package} title="Orders" subtitle="Track current and past orders" onPress={() => router.push('/orders')}/><AccountRow icon={Heart} title="Wishlist" subtitle="Your saved pieces" onPress={() => router.push('/wishlist')}/><AccountRow icon={Bell} title="Notifications" subtitle={unread ? `${unread} unread updates` : 'No unread updates'} onPress={() => router.push('/notifications')}/></Section>
    <Section title="PERSONAL"><AccountRow icon={UserRound} title="Personal information" subtitle="Name, email and profile details" onPress={() => router.push('/profile/edit')}/><AccountRow icon={MapPin} title="Addresses" subtitle="Manage delivery addresses" onPress={() => router.push('/profile/addresses')}/><AccountRow icon={ShieldCheck} title="Security" subtitle="Password and account security" onPress={() => router.push('/profile/security')}/></Section>
    <Section title="PREFERENCES"><AccountRow icon={Settings} title="Settings" subtitle="Notifications, privacy and preferences" onPress={() => router.push('/profile/settings')}/></Section>
    <Pressable style={styles.logout} onPress={async()=>{await logout();router.replace('/(auth)/login')}}><LogOut size={17} color={colors.danger}/><Text style={styles.logoutText}>Sign out</Text></Pressable>
    <View style={styles.footer}><Text style={styles.footerBrand}>ORYN</Text><Text style={styles.footerText}>Quiet objects. Considered choices.</Text></View>
  </ScrollView></View>;
}
function Section({title,children}:{title:string;children:ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},content:{padding:spacing.xl,paddingTop:62,paddingBottom:50},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{...typography.label,color:colors.textMuted,letterSpacing:1.4},title:{...typography.display,fontSize:31,lineHeight:36,marginTop:5},bell:{width:44,height:44,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},dot:{position:'absolute',right:10,top:9,width:6,height:6,backgroundColor:colors.accent},identity:{marginTop:30,padding:18,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,flexDirection:'row',alignItems:'center',gap:14},avatar:{width:48,height:48,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'center'},avatarText:{...typography.h2,color:colors.accent},identityCopy:{flex:1},name:{...typography.bodyMedium},email:{...typography.caption,color:colors.textSecondary,marginTop:3},section:{marginTop:34},sectionTitle:{...typography.label,color:colors.textMuted,letterSpacing:1.3,marginBottom:2},logout:{marginTop:36,minHeight:52,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',gap:10},logoutText:{...typography.bodyMedium,color:colors.danger},footer:{marginTop:46,paddingTop:26,borderTopWidth:1,borderColor:colors.border},footerBrand:{...typography.h2,letterSpacing:3},footerText:{...typography.caption,color:colors.textMuted,marginTop:5}});
