import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { MapPin, Plus, Trash2, Check } from 'lucide-react-native';
import { router } from 'expo-router';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { Text } from '@/components/ui/Text';
import { addressApi, type Address } from '@/services/api';
import { colors, spacing, typography } from '@/theme';

const empty = { label:'Home', firstName:'', lastName:'', line1:'', line2:'', city:'', state:'', postalCode:'', country:'Pakistan', phone:'', isDefault:true };
export default function Addresses(){
 const [items,setItems]=useState<Address[]>([]); const [form,setForm]=useState(empty); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
 const load=async()=>{try{setError(null);setItems(await addressApi.list())}catch(e){setError(e instanceof Error?e.message:'Unable to load addresses.')}}; useEffect(()=>{void load()},[]);
 const field=(key:keyof typeof form)=>(value:string)=>setForm(v=>({...v,[key]:value}));
 const save=async()=>{setLoading(true);try{await addressApi.create(form);setForm(empty);setShow(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save address.')}finally{setLoading(false)}};
 const remove=async(id:string)=>{Alert.alert('Remove address','This delivery address will be removed.',[{text:'Cancel',style:'cancel'},{text:'Remove',style:'destructive',onPress:async()=>{await addressApi.remove(id);await load()}}])};
 return <ScrollView style={styles.screen} contentContainerStyle={styles.container}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><View style={styles.head}><View><Text style={styles.kicker}>DELIVERY</Text><Text style={styles.title}>Addresses</Text></View><Pressable style={styles.add} onPress={()=>setShow(v=>!v)}><Plus size={18} color={colors.text}/></Pressable></View>{error?<Text style={styles.error}>{error}</Text>:null}
 {items.map(a=><View key={a.id} style={styles.address}><View style={styles.addressIcon}><MapPin size={18} color={colors.accent}/></View><View style={styles.addressMain}><View style={styles.addressTitle}><Text style={styles.label}>{a.label}</Text>{a.isDefault?<View style={styles.default}><Check size={11} color={colors.accent}/><Text style={styles.defaultText}>Default</Text></View>:null}</View><Text style={styles.copy}>{a.firstName} {a.lastName}{'\n'}{a.line1}{a.line2?`\n${a.line2}`:''}{'\n'}{a.city}{a.state?`, ${a.state}`:''} {a.postalCode}{'\n'}{a.country} · {a.phone}</Text><Pressable onPress={()=>remove(a.id)} style={styles.remove}><Trash2 size={15} color={colors.danger}/><Text style={styles.removeText}>Remove</Text></Pressable></View></View>)}
 {!items.length&&!show?<View style={styles.empty}><MapPin size={22} color={colors.textMuted}/><Text style={styles.emptyTitle}>No saved addresses</Text><Text style={styles.copy}>Add a delivery address once and reuse it at checkout.</Text></View>:null}
 {show?<View style={styles.form}><Text style={styles.formTitle}>New delivery address</Text><Input label="Label" value={form.label} onChangeText={field('label')} /><View style={styles.row}><View style={styles.half}><Input label="First name" value={form.firstName} onChangeText={field('firstName')} /></View><View style={styles.half}><Input label="Last name" value={form.lastName} onChangeText={field('lastName')} /></View></View><Input label="Address" value={form.line1} onChangeText={field('line1')} /><Input label="Apartment / suite" value={form.line2} onChangeText={field('line2')} /><View style={styles.row}><View style={styles.half}><Input label="City" value={form.city} onChangeText={field('city')} /></View><View style={styles.half}><Input label="Postal code" value={form.postalCode} onChangeText={field('postalCode')} /></View></View><Input label="State / province" value={form.state} onChangeText={field('state')} /><Input label="Country" value={form.country} onChangeText={field('country')} /><Input label="Phone" value={form.phone} onChangeText={field('phone')} keyboardType="phone-pad" /><Button label={loading?'Saving…':'Save address'} loading={loading} disabled={loading} onPress={save} /></View>:null}</ScrollView>
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:colors.background},container:{padding:spacing.xl,paddingTop:spacing.xxl,paddingBottom:50},back:{...typography.body,color:colors.accent,marginBottom:spacing.xxxl},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},kicker:{...typography.overline},title:{...typography.h1,fontSize:34,marginTop:4},add:{width:42,height:42,borderWidth:1,borderColor:colors.borderStrong,alignItems:'center',justifyContent:'center'},error:{...typography.caption,color:colors.danger,marginTop:18},address:{marginTop:20,borderTopWidth:1,borderColor:colors.border,paddingVertical:18,flexDirection:'row'},addressIcon:{width:40,height:40,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'center',marginRight:14},addressMain:{flex:1},addressTitle:{flexDirection:'row',alignItems:'center',gap:9},label:{...typography.body,fontWeight:'600'},copy:{...typography.body,color:colors.textSecondary,marginTop:6,lineHeight:21},default:{flexDirection:'row',alignItems:'center',gap:3},defaultText:{...typography.caption,color:colors.accent},remove:{flexDirection:'row',alignItems:'center',gap:6,marginTop:12},removeText:{...typography.caption,color:colors.danger},empty:{borderTopWidth:1,borderBottomWidth:1,borderColor:colors.border,paddingVertical:30,marginTop:24,alignItems:'center'},emptyTitle:{...typography.bodyMedium,marginTop:10},form:{marginTop:28,borderTopWidth:1,borderColor:colors.border,paddingTop:22},formTitle:{...typography.h3,marginBottom:18},row:{flexDirection:'row',gap:10},half:{flex:1}});
