import express from 'express';
import { authRouter } from './modules/auth/auth.routes';
import { productsRouter } from './modules/products/products.routes';
import { categoriesRouter } from './modules/categories/categories.routes';
import { cartRouter } from './modules/cart/cart.routes';
import { wishlistRouter } from './modules/wishlist/wishlist.routes';
import { ordersRouter } from './modules/orders/orders.routes';
import { reviewsRouter } from './modules/reviews/reviews.routes';
import { notificationsRouter } from './modules/notifications/notifications.routes';
import { addressesRouter } from './modules/addresses/addresses.routes';
import { paymentsRouter } from './modules/payments/payments.routes';
import { adminRouter } from './modules/admin/admin.routes';
import { errorHandler } from './middleware/errorHandler';
import { requestId } from './middleware/requestId';
import { rateLimit } from './middleware/rateLimit';
import { idempotency } from './middleware/idempotency';
import { applySecurity } from './common/security';

export function createApp() {
  const app = express();
  applySecurity(app);
  app.use(requestId);
  app.use(express.json({ limit: '1mb' }));
  app.use(rateLimit({ windowMs: 60_000, max: 240 }));
  app.use(idempotency());
  app.get('/health', (_req, res) => res.json({ status: 'ok', service: 'oryn-api' }));
  app.use('/api/auth', authRouter);
  app.use('/api/products', productsRouter);
  app.use('/api/categories', categoriesRouter);
  app.use('/api/cart', cartRouter);
  app.use('/api/wishlist', wishlistRouter);
  app.use('/api/orders', ordersRouter);
  app.use('/api/reviews', reviewsRouter);
  app.use('/api/notifications', notificationsRouter);
  app.use('/api/addresses', addressesRouter);
  app.use('/api/payments', paymentsRouter);
  app.use('/api/admin', adminRouter);
  app.use((_req, res) => res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Route not found' } }));
  app.use(errorHandler);
  return app;
}
